FROM node:20-alpine

RUN apk add --no-cache python3 py3-pip bash

# Pin formatter versions
RUN npm install -g prettier@3.7.4 \
 && pip install black==25.12.0 isort==7.0.0 --break-system-packages

WORKDIR /repo
ENTRYPOINT ["npm"]
